<div class="table-half" style="margin-right:20px!important;">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
        <thead>
<tr> 
          <th colspan="4">Tolérances diamètre<strong> 4 %</strong></th>
        </tr>
        <tr> 
          <th>Dia. nominal mm</th>
          <th>Dia. maximal mm</th>
          <th>Dia. nominal pouces</th>
          <th>Dia. maximal pouces</th>
        </tr>
</thead>
        <tbody>
<tr> 
          <td>10</td>
          <td>10.40</td>
          <td>3/8</td>
          <td>0.39</td>
        </tr>
        <tr> 
          <td>11</td>
          <td>11.45</td>
          <td>7/16</td>
          <td>0.45</td>
        </tr>
        <tr> 
          <td>12</td>
          <td>12.50</td>
          <td>1/2</td>
          <td>0.52</td>
        </tr>
        <tr> 
          <td>14</td>
          <td>14.55</td>
          <td>9/16</td>
          <td>0.59</td>
        </tr>
        <tr> 
          <td>15</td>
          <td>15.60</td>
          <td>5/8</td>
          <td>0.65</td>
        </tr>
        <tr> 
          <td>16</td>
          <td>16.65</td>
          <td>3/4</td>
          <td>0.78</td>
        </tr>
        <tr> 
          <td>18</td>
          <td>18.70</td>
          <td>7/8</td>
          <td>0.91</td>
        </tr>
        <tr> 
          <td>20</td>
          <td>20.80</td>
          <td>1</td>
          <td>1.04</td>
        </tr>
        <tr> 
          <td>22</td>
          <td>22.90</td>
          <td>1-1/8</td>
          <td>1.17</td>
        </tr>
        <tr> 
          <td>24</td>
          <td>25.00</td>
          <td>1-1/4</td>
          <td>1.30</td>
        </tr>
        <tr> 
          <td>26</td>
          <td>27.05</td>
          <td>1-3/8</td>
          <td>1.43</td>
        </tr>
        <tr> 
          <td>28</td>
          <td>29.10</td>
          <td>1-1/2</td>
          <td>1.56</td>
        </tr>
        <tr> 
          <td>30</td>
          <td>31.20</td>
          <td>1-5/8</td>
          <td>1.69</td>
        </tr>
        <tr> 
          <td>32</td>
          <td>33.30</td>
          <td>1-3/4</td>
          <td>1.82</td>
        </tr>
        <tr> 
          <td>34</td>
          <td>35.35</td>
          <td>1-7/8</td>
          <td>1.95</td>
        </tr>
        <tr> 
          <td>36</td>
          <td>37.45</td>
          <td>2</td>
          <td>2.08</td>
        </tr>
</tbody>
      </table>
</div>
<div class="table-half" style="margin-right:0px!important;">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
        <thead>
		<tr> 
          <th colspan="4">Tolérances diamètre<strong> 5 %</strong></th>
        </tr>
        <tr> 
          <th>Dia. nominal mm</th>
          <th>Dia. maximal mm</th>
          <th>Dia. nominal pouces</th>
          <th>Dia. maximal pouces</th>
        </tr>
</thead>
        <tbody>
<tr> 
          <td>10</td>
          <td>10.50</td>
          <td>3/8</td>
          <td>0.395</td>
        </tr>
        <tr> 
          <td>11</td>
          <td>11.50</td>
          <td>7/16</td>
          <td>0.46</td>
        </tr>
        <tr> 
          <td>12</td>
          <td>12.60</td>
          <td>1/2</td>
          <td>0.525</td>
        </tr>
        <tr> 
          <td>14</td>
          <td>14.70</td>
          <td>9/16</td>
          <td>0.59</td>
        </tr>
        <tr> 
          <td>15</td>
          <td>15.70</td>
          <td>5/8</td>
          <td>0.65</td>
        </tr>
        <tr> 
          <td>16</td>
          <td>16.80</td>
          <td>3/4</td>
          <td>0.79</td>
        </tr>
        <tr> 
          <td>18</td>
          <td>18.90</td>
          <td>7/8</td>
          <td>0.92</td>
        </tr>
        <tr> 
          <td>20</td>
          <td>21.00</td>
          <td>1</td>
          <td>1.05</td>
        </tr>
        <tr> 
          <td>22</td>
          <td>23.10</td>
          <td>1-1/8</td>
          <td>1.18</td>
        </tr>
        <tr> 
          <td>24</td>
          <td>25.20</td>
          <td>1-1/4</td>
          <td>1.31</td>
        </tr>
        <tr> 
          <td>26</td>
          <td>27.30</td>
          <td>1-3/8</td>
          <td>1.44</td>
        </tr>
        <tr> 
          <td>28</td>
          <td>29.40</td>
          <td>1-1/2</td>
          <td>1.58</td>
        </tr>
        <tr> 
          <td>30</td>
          <td>31.50</td>
          <td>1-5/8</td>
          <td>1.71</td>
        </tr>
        <tr> 
          <td>32</td>
          <td>33.60</td>
          <td>1-3/4</td>
          <td>1.84</td>
        </tr>
        <tr> 
          <td>34</td>
          <td>35.70</td>
          <td>1-7/8</td>
          <td>1.97</td>
        </tr>
        <tr> 
          <td>36</td>
          <td>37.80</td>
          <td>2</td>
          <td>2.10</td>
        </tr>
</tbody>
      </table>
      </div>