<div class="table-half">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
  <thead>
  <tr>
  	<th colspan="3">Dimensions (inch) for Becket Loops</th>
  </tr>
  <tr>
    <th>Nominal<br>wire rope diameter</th>
    <th>Nominal<br>loop cable diameter</th>
    <th>Nominal<br>loop length</th>
  </tr>
</thead>
  <tbody>
<tr>
    <td>3/8</td>
    <td>3/32</td>
    <td>3</td>
  </tr>
  <tr>
    <td>7/16</td>
    <td>3/32</td>
    <td>3</td>
  </tr>
  <tr>
    <td>1/2</td>
    <td>3/32</td>
    <td>3</td>
  </tr>
  <tr>
    <td>9/16</td>
    <td>3/32</td>
    <td>3</td>
  </tr>
  <tr>
    <td>5/8</td>
    <td>3/32</td>
    <td>3</td>
  </tr>
  <tr>
    <td>3/4</td>
    <td>1/8</td>
    <td>3</td>
  </tr>
  <tr>
    <td>7/8</td>
    <td>1/8</td>
    <td>3</td>
  </tr>
  <tr>
    <td>1</td>
    <td>3/16</td>
    <td>4</td>
  </tr>
  <tr>
    <td>1-1/8</td>
    <td>3/16</td>
    <td>4</td>
  </tr>
  <tr>
    <td>1-1/4</td>
    <td>3/16</td>
    <td>4</td>
  </tr>
  <tr>
    <td>1-3/8</td>
    <td>1/4</td>
    <td>4</td>
  </tr>
  <tr>
    <td>1-1/2</td>
    <td>1/4</td>
    <td>4</td>
  </tr>
  <tr>
    <td>1-3/4</td>
    <td>1/4</td>
    <td>4</td>
  </tr>
</tbody>
</table>
</div>
