<div class="table-half">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
  <thead>
  <tr>
  	<th colspan="5">Dimensions for DIN 3091 Solid Thimble Splice</th>
  </tr>
<tr>
    <th>Nominal<br>wire rope diameter<br>mm</th>
    <th>Nominal<br>wire rope diameter<br>inch</th>
    <th>Nominal<br>thimble size #</th>
    <th>Raw bore diameter<br>mm</th>
    <th>Max. bore diameter<br>mm</th>
  </tr>
</thead>
  <tbody>
<tr>
    <td>14</td>
    <td>N/A</td>
    <td>14</td>
    <td>29</td>
    <td>35</td>
  </tr>
  <tr>
    <td>16</td>
    <td>N/A</td>
    <td>16</td>
    <td>32</td>
    <td>40</td>
  </tr>
  <tr>
    <td>18</td>
    <td>N/A</td>
    <td>18</td>
    <td>35</td>
    <td>45</td>
  </tr>
  <tr>
    <td>20</td>
    <td>N/A</td>
    <td>20</td>
    <td>40</td>
    <td>50</td>
  </tr>
  <tr>
    <td>22</td>
    <td>N/A</td>
    <td>22</td>
    <td>43</td>
    <td>55</td>
  </tr>
  <tr>
    <td>24</td>
    <td>N/A</td>
    <td>24</td>
    <td>46</td>
    <td>60</td>
  </tr>
  <tr>
    <td>26</td>
    <td>N/A</td>
    <td>26</td>
    <td>49</td>
    <td>65</td>
  </tr>
  <tr>
    <td>28</td>
    <td>N/A</td>
    <td>28</td>
    <td>52</td>
    <td>70</td>
  </tr>
  <tr>
    <td>30</td>
    <td>N/A</td>
    <td>32</td>
    <td>58</td>
    <td>80</td>
  </tr>
  <tr>
    <td>32</td>
    <td>N/A</td>
    <td>32</td>
    <td>58</td>
    <td>80</td>
  </tr>
  <tr>
    <td>34</td>
    <td>N/A</td>
    <td>36</td>
    <td>59</td>
    <td>90</td>
  </tr>
  <tr>
    <td>36</td>
    <td>N/A</td>
    <td>36</td>
    <td>59</td>
    <td>90</td>
  </tr>
</tbody>
</table>
</div>