<div class="table-full">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
  <thead>
  <tr>
  	<th colspan="6">Dimensions for Loop Back Splice with American Style HD Thimble</th>
  </tr>
<tr>
    <th>Nominal<br>wire rope diameter<br>mm</th>
    <th>Nominal<br>wire rope diameter<br>inch</th>
    <th>with<br>HD thimble size</th>
    <th>Nominal<br>D<br>inch</th>
    <th>Nominal<br>L<br>inch</th>
    <th>Nominal<br>thickness<br>inch</th>
  </tr>
</thead>
<tbody>
<tr>
    <td>6</td>
    <td>1/4</td>
    <td>1/4</td>
    <td>0.88</td>
    <td>1.63</td>
    <td>0.41</td>
  </tr>
  <tr>
    <td>8</td>
    <td>5/16</td>
    <td>5/16</td>
    <td>1.06</td>
    <td>1.88</td>
    <td>0.50</td>
  </tr>
  <tr>
    <td>9</td>
    <td>3/8</td>
    <td>3/8</td>
    <td>1.13</td>
    <td>2.13</td>
    <td>0.63</td>
  </tr>
  <tr>
    <td>10</td>
    <td>&nbsp;</td>
    <td>7/16</td>
    <td>1.25</td>
    <td>2.38</td>
    <td>0.72</td>
  </tr>
  <tr>
    <td>11</td>
    <td>7/16</td>
    <td>7/16</td>
    <td>1.25</td>
    <td>2.38</td>
    <td>0.72</td>
  </tr>
  <tr>
    <td>12</td>
    <td>&nbsp;</td>
    <td>1/2</td>
    <td>1.50</td>
    <td>2.75</td>
    <td>0.81</td>
  </tr>
  <tr>
    <td>13</td>
    <td>1/2</td>
    <td>1/2</td>
    <td>1.50</td>
    <td>2.75</td>
    <td>0.88</td>
  </tr>
  <tr>
    <td>14</td>
    <td>9/16</td>
    <td>9/16</td>
    <td>1.50</td>
    <td>2.75</td>
    <td>0.88</td>
  </tr>
  <tr>
    <td>16</td>
    <td>5/8</td>
    <td>5/8</td>
    <td>1.75</td>
    <td>3.25</td>
    <td>0.97</td>
  </tr>
  <tr>
    <td>18</td>
    <td>&nbsp;</td>
    <td>3/4</td>
    <td>2.00</td>
    <td>3.75</td>
    <td>1.22</td>
  </tr>
  <tr>
    <td>19</td>
    <td>3/4</td>
    <td>3/4</td>
    <td>2.00</td>
    <td>3.75</td>
    <td>1.22</td>
  </tr>
  <tr>
    <td>20</td>
    <td>&nbsp;</td>
    <td>7/8</td>
    <td>2.25</td>
    <td>4.25</td>
    <td>1.38</td>
  </tr>
  <tr>
    <td>22</td>
    <td>7/8</td>
    <td>7/8</td>
    <td>2.25</td>
    <td>4.25</td>
    <td>1.38</td>
  </tr>
  <tr>
    <td>24</td>
    <td>&nbsp;</td>
    <td>1</td>
    <td>2.50</td>
    <td>4.50</td>
    <td>1.56</td>
  </tr>
  <tr>
    <td>26</td>
    <td>1</td>
    <td>1</td>
    <td>2.50</td>
    <td>4.50</td>
    <td>1.56</td>
  </tr>
  <tr>
    <td>28</td>
    <td>1-1/8</td>
    <td>1-1/8</td>
    <td>2.88</td>
    <td>5.13</td>
    <td>1.81</td>
  </tr>
  <tr>
    <td>30</td>
    <td>1-1/8</td>
    <td>1-1/4</td>
    <td>3.50</td>
    <td>6.50</td>
    <td>2.19</td>
  </tr>
  <tr>
    <td>32</td>
    <td>1-1/4</td>
    <td>1-1/4</td>
    <td>3.50</td>
    <td>6.50</td>
    <td>2.19</td>
  </tr>
</tbody>
<tfoot>
	<tr>
		<td colspan="6">
		<div class="footnote">
            <p><b>Note:</b> Aluminum Loop Back Splices onto PYTHON® wire rope may require different sleeve sizes. Please ask for details and prices.</p>
		</div>
		</td>
	</tr>
</tfoot>
</table>
</div>
