<div class="table-half">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
  <thead>
  <tr>
  	<th colspan="3">Dimensions for Loop Back Aluminum Sleeve Splice<br><span>Different loop dimensions upon request.</span></th>
  </tr>
<tr>
    <th>Nominal wire rope diameter mm</th>
    <th>Nominal wire rope diameter inch</th>
    <th>Eye length &amp; width inch</th>
  </tr>
</thead>
 <tbody>
 <tr>
    <td>6</td>
    <td>1/4</td>
    <td>4x2</td>
  </tr>
  <tr>
    <td>8</td>
    <td>5/16</td>
    <td>4x2</td>
  </tr>
  <tr>
    <td>9</td>
    <td>3/8</td>
    <td>6x3</td>
  </tr>
  <tr>
    <td>10</td>
    <td>&nbsp;</td>
    <td>6x3</td>
  </tr>
  <tr>
    <td>11</td>
    <td>7/16</td>
    <td>7x3-1/2</td>
  </tr>
  <tr>
    <td>12</td>
    <td>&nbsp;</td>
    <td>8x4</td>
  </tr>
  <tr>
    <td>13</td>
    <td>1/2</td>
    <td>8x4</td>
  </tr>
  <tr>
    <td>14</td>
    <td>9/16</td>
    <td>9x4-1/2</td>
  </tr>
  <tr>
    <td>16</td>
    <td>5/8</td>
    <td>10x5</td>
  </tr>
<tr>
    <td>18</td>
    <td>&nbsp;</td>
    <td>12x6</td>
  </tr>
  <tr>
    <td>19</td>
    <td>3/4</td>
    <td>12x6</td>
  </tr>
  <tr>
    <td>20</td>
    <td>&nbsp;</td>
    <td>12x6</td>
  </tr>
  <tr>
    <td>22</td>
    <td>7/8</td>
    <td>14x7</td>
  </tr>
  <tr>
    <td>24</td>
    <td>&nbsp;</td>
    <td>16x8</td>
  </tr>
  <tr>
    <td>26</td>
    <td>1</td>
    <td>16x8</td>
  </tr>
  <tr>
    <td>28</td>
    <td>1-1/8</td>
    <td>18x9</td>
  </tr>
  <tr>
    <td>30</td>
    <td>1-1/8</td>
    <td>20x10</td>
  </tr>
  <tr>
    <td>32</td>
    <td>1-1/4</td>
    <td>20x10</td>
  </tr>
</tbody>
<tfoot>
	<tr>
		<td colspan="3">
		<div class="footnote">
            <p><b>Note:</b> Aluminum Loop Back Splices onto PYTHON® wire rope may require different sleeve sizes.
Please ask for details and prices.</p>
		</div>
		</td>
	</tr>
</tfoot>
</table>
</div>
