<div class="table-half">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
  <thead>
<tr>
    <th colspan="5">Python® Compac 35 Euro Style</th>
  </tr>
   <tr>
    <th rowspan="3">Rope dia. mm</th>
    <th rowspan="3">Rope dia. inch</th>
    <th colspan="4">Minimum Breaking Strength</th>
    <th rowspan="3">Weight per meter kg</th>
  </tr>
  <tr>
  <th colspan="2">Compac® 35</th>
  <th colspan="2">Compac® 35 PLUS</th>
  </tr>
  <!--
  <tr>
    <th rowspan="2">Rope dia. mm</th>
    <th rowspan="2">Rope dia. inch</th>
    <th colspan="2">Minimum Breaking Strength</th>
    <th rowspan="2">Weight per meter kg</th>
  </tr>
  --> <!-- Old Syntax -->
  <tr>
    <th>kN</th>
    <th>tons 2,000 lbs</th>
    <th>kN</th> <!-- New element -->
    <th>tons 2,000 lbs</th> <!-- New element -->

  </tr>
</thead>
  <tbody>
<tr>
    <td>8</td>
    <td>5/16</td>
    <td>57</td>
    <td>6.4</td>
     <td>&nbsp;</td> <!-- New element on each row -->
    <td>&nbsp;</td> <!-- New element on each row -->
    <td>0.29</td>
  </tr>
  <tr>
    <td>9</td>
    <td>&nbsp;</td>
    <td>73</td>
    <td>8.2</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>0.36</td>
  </tr>
  <tr>
    <td>10</td>
    <td>&nbsp;</td>
    <td>98</td>
    <td>11.0</td> 
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>0.44</td>
  </tr>
  <tr>
    <td>11</td>
    <td>7/16</td>
    <td>118</td>
    <td>13.2</td> 
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>0.54</td>
  </tr>
  <tr>
    <td>12</td>
    <td>&nbsp;</td>
    <td>140</td>
    <td>15.7</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>0.65</td>
  </tr>
  <tr>
    <td>13</td>
    <td>1/2</td>
    <td>162</td>
    <td>18.2</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>0.84</td>
  </tr>
  <tr>
    <td>14</td>
    <td>9/16</td>
    <td>196 </td>
    <td>22.0</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>0.99</td>
  </tr>
  <tr>
    <td>15</td>
    <td>&nbsp;</td>
    <td>226</td>
    <td>25.4</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>1.13</td>
  </tr>
  <tr>
    <td>16</td>
    <td>5/8</td>
    <td>253</td>
    <td>28.5</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>1.29</td>
  </tr>
  <tr>
    <td>17</td>
    <td>&nbsp;</td>
    <td>287</td>
    <td>32.2</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>1.44</td>
  </tr>
  <tr>
    <td>18</td>
    <td>&nbsp;</td>
    <td>317</td>
    <td>35.6</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>1.59</td>
  </tr>
  <tr>
    <td>19</td>
    <td>3/4</td>
    <td>358</td>
    <td>40.2</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>1.78</td>
  </tr>
  <tr>
    <td>20</td>
    <td>&nbsp;</td>
    <td>402</td>
    <td>45.1</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>2.01</td>
  </tr>
  <tr>
    <td>21</td>
    <td>&nbsp;</td>
    <td>444</td>
    <td>49.9</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>2.19</td>
  </tr>
  <tr>
    <td>22</td>
    <td>7/8</td>
    <td>482</td>
    <td>54.1</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>2.41</td>
  </tr>
  <tr>
    <td>23</td>
    <td>&nbsp;</td>
    <td>530</td>
    <td>59.6</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>2.67</td>
  </tr>
  <tr>
    <td>24</td>
    <td>&nbsp;</td>
    <td>564</td>
    <td>63.5</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>2.84</td>
  </tr>
  <tr>
    <td>25</td>
    <td>1</td>
    <td>615</td>
    <td>69.1</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>3.06</td>
  </tr>
  <tr>
    <td>26</td>
    <td>&nbsp;</td>
    <td>667</td>
    <td>74.9</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>3.35</td>
  </tr>
  <tr>
    <td>28</td>
    <td>1-1/8</td>
    <td>771</td>
    <td>86.6</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>3.84</td>
  </tr>
  <tr>
    <td>30</td>
    <td>&nbsp;</td>
    <td>886</td>
    <td>99.5</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>4.46</td>
  </tr>
  <tr>
    <td>32</td>
    <td>1-1/4</td>
    <td>980</td>
    <td>110.0</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>5.00</td>
  </tr>
  <tr>
    <td>34</td>
    <td>&nbsp;</td>
    <td>1,127</td>
    <td>126.7</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>5.74</td>
  </tr>
  <tr>
    <td>35</td>
    <td>1-3/8</td>
    <td>1,190</td>
    <td>133.7</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>6.06</td>
  </tr>
  <tr>
    <td>36</td>
    <td>&nbsp;</td>
    <td>1,260</td>
    <td>141.6</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>6.42</td>
  </tr>
  <tr>
    <td>37</td>
    <td>&nbsp;</td>
    <td>1,323</td>
    <td>148.7</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>6.74</td>
  </tr>
  <tr>
    <td>38</td>
    <td>1-1/2</td>
    <td>1,409</td>
    <td>158.3</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>7.18</td>
  </tr>
  <tr>
    <td>40</td>
    <td>&nbsp;</td>
    <td>1,557</td>
    <td>175.0</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>7.93</td>
  </tr>
  <tr>
    <td>41</td>
    <td>1-5/8</td>
    <td>1,624</td>
    <td>182.5</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>8.27</td>
  </tr>
  <tr>
    <td>42</td>
    <td>&nbsp;</td>
    <td>1,703</td>
    <td>191.4</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>8.67</td>
  </tr>
  <tr>
    <td>44</td>
    <td>1-3/4</td>
    <td>1,862</td>
    <td>209.3</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>9.48</td>
  </tr>
  <tr>
    <td>46</td>
    <td>&nbsp;</td>
    <td>2,048</td>
    <td>230.2</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>10.40</td>
  </tr>
  <tr>
    <td>48</td>
    <td>1-7/8</td>
    <td>2,231</td>
    <td>250.8</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>11.40</td>
  </tr>
  <tr>
    <td>50</td>
    <td>2</td>
    <td>2,406</td>
    <td>270.4</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>12.30 </td>
  </tr>
  <tr>
    <td>52</td>
    <td>&nbsp;</td>
    <td>2,597</td>
    <td>291.9</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>13.20</td>
  </tr>
  <tr>
    <td>54</td>
    <td>2-1/4</td>
    <td>2,796</td>
    <td>314.3</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>14.20</td>
  </tr>
  <tr>
    <td>56</td>
    <td>&nbsp;</td>
    <td>3,000</td>
    <td>337.2</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>15.30</td>
  </tr>
  <tr>
    <td>58</td>
    <td>&nbsp;</td>
    <td>3,267</td>
    <td>367.2</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>16.60</td>
  </tr>
  <tr>
    <td>60</td>
    <td>2-3/8</td>
    <td>3,480</td>
    <td>391.1</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>17.70</td>
  </tr>
  <tr>
    <td>62</td>
    <td>&nbsp;</td>
    <td>3,699</td>
    <td>415.7</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>18.80</td>
  </tr>
  <tr>
    <td>64</td>
    <td>2-1/2</td>
    <td>3,928</td>
    <td>441.5</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>20.00</td>
  </tr>
  <tr>
    <td>66</td>
    <td>&nbsp;</td>
    <td>4,199</td>
    <td>471.9</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>21.70</td>
  </tr>
  <tr>
    <td>68</td>
    <td>&nbsp;</td>
    <td>4,443</td>
    <td>499.4</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>22.60</td>
  </tr>
  <tr>
    <td>70</td>
    <td>2-3/4</td>
    <td>4,742</td>
    <td>533.0</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>24.10</td>
  </tr>
  <tr>
    <td>72</td>
    <td>&nbsp;</td>
    <td>4,993</td>
    <td>561.2</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>25.40</td>
  </tr>
  <tr>
    <td>74</td>
    <td>&nbsp;</td>
    <td>5,299</td>
    <td>595.6</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>27.00</td>
  </tr>
  <tr>
    <td>76</td>
    <td>3</td>
    <td>5,583</td>
    <td>627.5</td>
      <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>28.40</td>
  </tr>
  <tr>
    <td>78</td>
    <td>&nbsp;</td>
    <td>5,879</td>
    <td>660.8</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>29.90</td>
  </tr>
  <tr>
    <td>80</td>
    <td>3-1/8</td>
    <td>6,143</td>
    <td>690.5</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>31.30</td>
  </tr>
</tbody>
</table>
</div>

<div class="table-half">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
  <thead>
<tr>
    <th colspan="5">Python® Compac 35 PLUS</th>
  </tr>
  <tr>
    <th rowspan="2">Rope dia. mm</th>
    <th rowspan="2">Rope dia. inch</th>
    <th colspan="2">Minimum Breaking Strength</th>
    <th rowspan="2">Weight per meter kg</th>
  </tr>
  <tr>
    <th>kN</th>
    <th>tons 2,000 lbs</th>
  </tr>
</thead>
  <tbody>
    <tr>
      <td>16</td>
      <td>5/8</td>
      <td>272</td>
      <td>30.6</td>
      <td>1.29</td>
    </tr>
    <tr>
      <td>19</td>
      <td>3/4</td>
      <td>382</td>
      <td>42.9</td>
      <td>1.78</td>
    </tr>
    <tr>
      <td>22</td>
      <td></td>
      <td>503</td>
      <td>56.5</td>
      <td>2.38</td>
    </tr>
    <tr>
      <td></td>
      <td>7/8</td>
      <td>509</td>
      <td>57.2</td>
      <td>2.40</td>
    </tr>
    <tr>
      <td>23</td>
      <td></td>
      <td>550</td>
      <td>61.8</td>
      <td>2.67</td>
    </tr>
    <tr>
      <td>24</td>
      <td></td>
      <td>599</td>
      <td>67.3</td>
      <td>2.84</td>
    </tr>
    <tr>
      <td>25</td>
      <td></td>
      <td>656</td>
      <td>73.7</td>
      <td>3.12</td>
    </tr>
    <tr>
      <td></td>
      <td>1</td>
      <td>684</td>
      <td>76.9</td>
      <td>3.20</td>
    </tr>
    <tr>
      <td>26</td>
      <td></td>
      <td>696</td>
      <td>78.2</td>
      <td>3.35</td>
    </tr>
    <tr>
      <td>27</td>
      <td></td>
      <td>741</td>
      <td>83.2</td>
      <td>3.58</td>
    </tr>
    <tr>
      <td>28</td>
      <td></td>
      <td>798</td>
      <td>89.7</td>
      <td>3.60</td>
    </tr>
    <tr>
      <td></td>
      <td>1-1/8</td>
      <td>814</td>
      <td>91.5</td>
      <td>3.67</td>
    </tr>
    <tr>
      <td>29</td>
      <td></td>
      <td>851</td>
      <td>95.6</td>
      <td>4.12</td>
    </tr>
    <tr>
      <td>30</td>
      <td></td>
      <td>892</td>
      <td>100.3</td>
      <td>4.46</td>
    </tr>
    <tr>
      <td>31</td>
      <td></td>
      <td>976</td>
      <td>109.7</td>
      <td>4.73</td>
    </tr>
    <tr>
      <td></td>
      <td>1-1/4</td>
      <td>1,029</td>
      <td>115.6</td>
      <td>4.78</td>
    </tr>
    <tr>
      <td>32</td>
      <td></td>
      <td>1,085</td>
      <td>121.9</td>
      <td>5.03</td>
    </tr>
    <tr>
      <td>34</td>
      <td></td>
      <td>1,170</td>
      <td>131.5</td>
      <td>5.74</td>
    </tr>
  </tbody>
</table>
</div>