<div class="table-half">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
  <thead>
  <tr>
  	<th colspan="2">Dimensions (pouces) pour Épissure à boucle</th>
  </tr>
  <tr>
    <th width="50%">Diam. nom. câble métallique à 6 brins</th>
    <th>Crochets Longueur & Largeur</th>
  </tr>
</thead>
  <tbody>
<tr>
    <td>1/4</td>
    <td> 4x2</td>
  </tr>
  <tr>
    <td>5/16</td>
    <td>4x2</td>
  </tr>
  <tr>
    <td>3/8</td>
    <td>6x3</td>
  </tr>
  <tr>
    <td>7/16</td>
    <td>7x3-1/2</td>
  </tr>
  <tr>
    <td>1/2</td>
    <td>8x4</td>
  </tr>
  <tr>
    <td>9/16</td>
    <td>9x4-1/2</td>
  </tr>
  <tr>
    <td>5/8</td>
    <td>10x5</td>
  </tr>
  <tr>
    <td>3/4</td>
    <td>12x6</td>
  </tr>
  <tr>
    <td>7/8</td>
    <td>14x7</td>
  </tr>
  <tr>
    <td>1</td>
    <td>16x8</td>
  </tr>
  <tr>
    <td>1-1/8</td>
    <td>18x9</td>
  </tr>
  <tr>
    <td>1-1/4</td>
    <td>20x10</td>
  </tr>
  <tr>
    <td>1-3/8</td>
    <td>22x11</td>
  </tr>
  <tr>
    <td>1-1/2</td>
    <td>24x12</td>
  </tr>
  <tr>
    <td>1-3/4</td>
    <td>30x15</td>
  </tr>
  <tr>
    <td>2</td>
    <td>32x16</td>
  </tr>
  <tr>
    <td>2-1/4</td>
    <td>36x18</td>
  </tr>
  <tr>
    <td>2-1/2</td>
    <td>40x20</td>
  </tr>
</tbody>
</table>
</div>
