<div class="table-half">
<table class="data" border="0" cellspacing="0" cellpadding="0" width="100%">
  <thead>
  <tr><th></th></tr>
<tr>
    <th>Diam. nom. câble PYTHONᴹᴰ non rotatif</th>
    <th>Bouton torpille embouti et conique de longueur approx. en pouces</th>
  </tr>
</thead>
  <tbody>
<tr>
    <td>13</td>
    <td>3-5/8</td>
  </tr>
  <tr>
    <td>14</td>
    <td>3-5/8</td>
  </tr>
  <tr>
    <td>15</td>
    <td>3-5/8</td>
  </tr>
  <tr>
    <td>16</td>
    <td>4-3/16</td>
  </tr>
  <tr>
    <td>17</td>
    <td>4-3/16</td>
  </tr>
  <tr>
    <td>18</td>
    <td>4-3/16</td>
  </tr>
  <tr>
    <td>19</td>
    <td>4-7/8</td>
  </tr>
  <tr>
    <td>20</td>
    <td>4-7/8</td>
  </tr>
  <tr>
    <td>21</td>
    <td>4-7/8</td>
  </tr>
  <tr>
    <td>22</td>
    <td>4-7/8</td>
  </tr>
  <tr>
    <td>23</td>
    <td>6</td>
  </tr>
  <tr>
    <td>24</td>
    <td>6</td>
  </tr>
  <tr>
    <td>25</td>
    <td>6</td>
  </tr>
  <tr>
    <td>26</td>
    <td>6</td>
  </tr>
  <tr>
    <td>27</td>
    <td>6-7/8</td>
  </tr>
  <tr>
    <td>28</td>
    <td>6-7/8</td>
  </tr>
  <tr>
    <td>29</td>
    <td>6-7/8</td>
  </tr>
  <tr>
    <td>30</td>
    <td>7-3/8</td>
  </tr>
  <tr>
    <td>31</td>
    <td>7-3/8</td>
  </tr>
  <tr>
    <td>32</td>
    <td>7-3/8</td>
  </tr>
</tbody>
</table>
</div>